{{- if .Values.rbac.create -}}
{{- $name := printf "%s-justcd-agent" .Release.Name | trunc 45 | trimSuffix "-" -}}
{{- $sa := default $name .Values.serviceAccount.name -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}-identity
rules:
  {{- if not .Values.kubernetes.clusterId }}
  - apiGroups: [""]
    resources: [namespaces]
    resourceNames: [kube-system]
    verbs: [get]
  {{- end }}
  - nonResourceURLs: ["/version", "/api", "/api/*", "/apis", "/apis/*", "/openapi/*"]
    verbs: [get]
  - apiGroups: [authorization.k8s.io]
    resources: [selfsubjectaccessreviews]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}-identity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}-identity
subjects:
  - kind: ServiceAccount
    name: {{ $sa }}
    namespace: {{ .Release.Namespace }}
---
{{- if .Values.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}-workloads
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}-workloads
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}-workloads
subjects:
  - kind: ServiceAccount
    name: {{ $sa }}
    namespace: {{ .Release.Namespace }}
{{- else }}
{{- $namespaces := list -}}
{{- range .Values.profiles }}{{- range .namespaces }}{{- if not (hasSuffix "*" .) }}{{- $namespaces = append $namespaces . }}{{- end }}{{- end }}{{- end }}
{{- range $namespaces | uniq }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ . }}
rules:
  {{- toYaml $.Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $sa }}
    namespace: {{ $.Release.Namespace }}
---
{{- end }}
{{- end }}
{{- end }}
